---
- hosts: gsyt
  vars:
    package_state: latest
    chef_dk_src: "https://packages.chef.io/stable/el/{{ ansible_distribution_major_version }}/chefdk-{{ chef_dk_version }}.el{{ ansible_distribution_major_version }}.{{ ansible_machine }}.rpm"
    chef_dk_version: 0.19.6-1
    chef_repo_src: assets/chef-repo
    chef_repo_dst: /opt/automation/chef-repo
    yum_package_pip: python-pip
  roles:
    - { role: geerlingguy.repo-epel }
  tasks:
    - name: "Install Chef DK"
      yum:
        name: "{{ chef_dk_src }}"
        state: present
    - name: "Install Python pip"
      yum:
        name: "{{ yum_package_pip }}"
    - name: "Push Chef Repo"
      copy:
        src: "{{ chef_repo_src }}"
        dest: "{{ chef_repo_dst }}"
        force: yes
